matrix: 
    fast_finish: true     # set this flag to immediately finish build once one of the jobs fails. 

before_build:
    - nuget: restore

platform:
    - x86

configuration: Release

build:
    project: granes.sln

    # MSBuild verbosity level quiet|minimal|normal|detailed 
    verbosity: minimal

# scripts to run after build 
after_build: 
    - Release\granes_test.exe

# Our build scripts run tests automatically; we don't want AppVeyor 
# to try to detect them itself. 
test: off 
